### ISSUE TITLE
Multiple critical errors occurred

### ISSUE THREAD

**Issue by idesign2018** [banodoco/Dough#104]
### error log:
![image](https://github.com/banodoco/Dough/assets/42263070/5a1d16cc-8651-4557-a999-966926ebca88)

***

### The following is the answer I gave the error log to ChatGPT, for reference only：

1. **`ModuleNotFoundError: No module named 'numexpr'`**: This indicates that the `numexpr` module is not installed. To solve this problem, the missing `numexpr` module needs to be installed.

2. **`KeyError: 'PromptSchedule'`**: This appears to be because a non-existent `'PromptSchedule'` key was referenced somewhere. This could be in the configuration files or a part of the code where a non-existent class or key is referenced.

3. **`KeyError: 'file_paths'`**: This error usually occurs when the `'file_paths'` key is expected to be found in a dictionary but is not present. This could be because the program expects a list of file paths as output but none was generated.

To address these issues, you can follow these steps:

1. Install the `numexpr` module. This can be done using the command `pip install numexpr`.

2. Check the code or configuration files to ensure the `'PromptSchedule'` key is used correctly. Make sure that wherever this key is referenced, it is done accurately, and that the related configuration or data structure has this key defined properly.

3. For the `'file_paths'` error, examine the logic that generates the list of file paths to ensure that it can produce the list correctly when needed. It might be necessary to investigate why the expected output was not generated and ensure all necessary inputs are correctly provided.

You should start by addressing the installation issue of `numexpr`, then delve into the subsequent errors, adjusting according to the specific configuration and code structure.

***

According to the answer, I installed the "numexpr" module, but it still prompts that there is no "numexpr" module. I don't know the reason.

According to the installation method given by the author on two computers, there is no problem when generating pictures, but I encounter the same problem when generating animations. I also tried to install and run it in a virtual environment and a physical environment, and the same problem happened. I look forward to the author's help, thank you very much!

**Comment by piyushK52** [comment]
you are using your own conda environment on top of the dough-env this repo creates.. either only use conda (in that case you will need to install things manually) or use the dough-env

**Comment by idesign2018** [comment]
> 您正在此存储库创建的dough-env之上使用您自己的conda环境..要么仅使用conda（在这种情况下您将需要手动安装）或使用dough-env

How should I proceed?

**Comment by piyushK52** [comment]
one way could be to deactivate your conda environment and install things in dough-env. so after you deactivate the conda, follow these steps
1. run --> dough-env\Scripts\activate.bat
2. run --> pip install -r requirements.txt
3. delete ComfyUI and comfy_runner folder
4. start the app using ".\entrypoint.bat"

when you run any model the first time it will be slightly slow as it will install ComfyUI and comfy_runner but after that there won't be any lag

**Comment by idesign2018** [comment]
![image](https://github.com/banodoco/Dough/assets/42263070/259d1054-edd8-41dd-ad76-51b8afababf0)
I seem to have encountered a new problem

> one way could be to deactivate your conda environment and install things in dough-env. so after you deactivate the conda, follow these steps
> 
> 1. run --> dough-env\Scripts\activate.bat
> 2. run --> pip install -r requirements.txt
> 3. delete ComfyUI and comfy_runner folder
> 4. start the app using ".\entrypoint.bat"
> 
> when you run any model the first time it will be slightly slow as it will install ComfyUI and comfy_runner but after that there won't be any lag

**Comment by idesign2018** [comment]
I sent the answer to ChatGPT and I couldn't understand it at all
![image](https://github.com/banodoco/Dough/assets/42263070/7fd86219-b52b-450f-b075-48efa84561a0)

**Comment by idesign2018** [comment]
When I do not select Lora, RuntimeError is still displayed. When I select Lora, I am asked to verify the integrity of the Lora file. What is the reason? Lora was just downloaded

### No error message for Lora:
![image](https://github.com/banodoco/Dough/assets/42263070/c6f6d579-15ed-410e-b252-602279f2cff4)
![image](https://github.com/banodoco/Dough/assets/42263070/ce56d799-c6b1-421e-9c43-7ffd68d92d72)

### There is an error message from Lora:
![image](https://github.com/banodoco/Dough/assets/42263070/e9353b8e-817e-49cd-ae21-46fe46c120bc)
![image](https://github.com/banodoco/Dough/assets/42263070/b8de994c-827a-418d-9515-935b7a32cbf2)

**Comment by idesign2018** [comment]
### New errors encountered:
![image](https://github.com/banodoco/Dough/assets/42263070/adfc35b9-e73e-4f0f-be49-4ac4104d0d9d)
![image](https://github.com/banodoco/Dough/assets/42263070/89f1505f-9366-4ff4-be30-1a25efb1ce6e)

**Comment by piyushK52** [comment]
Hey I think your setup is broken maybe somewhere during the setup a wrong environment was selected. I will suggest you to do a fresh install and if possible record your setup process, so I can tell where you are going wrong. We will also add a portable version to the app in the next update (in a couple of days), so that you can just directly download and run it without any installation.

**Comment by idesign2018** [comment]
Since I don't know programming, I encountered many problems that I didn't know how to solve. I also installed this according to the steps on our github, but such a problem occurred. I have reinstalled it many times and still can't solve it.
### Looking forward to the release of the convenient version, thank you!

**Comment by zhaowtVincent** [comment]
<img width="908" alt="image" src="https://github.com/banodoco/Dough/assets/29684236/8a1070ec-a98c-429e-abca-605421f38fad">
same error

**Comment by piyushK52** [comment]
@zhaowtVincent can you share the complete error log?

**Comment by zhaowtVincent** [comment]
(venv) K:\project1\Dough>"K:\project1\Dough\scripts\entrypoint.bat"

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:5500
  Network URL: http://192.168.1.11:5500

INFO:app_logger:Starting runner
runner running
DEBUG:app_logger:cloning comfy repo
DEBUG:app_logger:Checking comfy requirements, please wait...
** ComfyUI startup time: 2024-05-20 11:13:22.834681
** Platform: Windows
** Python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
** Python executable: K:\project1\Dough\venv\Scripts\python.exe
** Log path: K:\project1\Dough\comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 49152 MB, total RAM 130943 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro RTX 8000 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.8.3)
### ComfyUI Revision: 2022 [e61755ea] | Released on '2024-02-26'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FizzleDorf Custom Nodes: Loaded

Import times for custom nodes:
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI_essentials
   0.2 seconds: K:\project1\Dough\ComfyUI\custom_nodes\comfyui-various
   0.2 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.2 seconds: K:\project1\Dough\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.5 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.5 seconds: K:\project1\Dough\ComfyUI\custom_nodes\steerable-motion
   0.7 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.8 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   1.1 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:4333
DEBUG:app_logger:Process 5364 (Port 4333)
DEBUG:app_logger:comfy server is running
FETCH DATA from: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
Update check done.
DEBUG:app_logger:checking file:
DEBUG:app_logger:WAS26.safetensors already present
INFO:app_logger:Restarting the server
DEBUG:app_logger:Process 5364 (Port 4333)
** ComfyUI startup time: 2024-05-20 11:14:17.774390
** Platform: Windows
** Python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
** Python executable: K:\project1\Dough\venv\Scripts\python.exe
** Log path: K:\project1\Dough\comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 49152 MB, total RAM 130943 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro RTX 8000 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### Loading: ComfyUI-Manager (V2.8.3)
### ComfyUI Revision: 2022 [e61755ea] | Released on '2024-02-26'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FizzleDorf Custom Nodes: Loaded

Import times for custom nodes:
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI_essentials
   0.4 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.5 seconds: K:\project1\Dough\ComfyUI\custom_nodes\steerable-motion
   0.7 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.8 seconds: K:\project1\Dough\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:4333
DEBUG:app_logger:Process 38476 (Port 4333)
DEBUG:app_logger:comfy server is running
DEBUG:app_logger:Updating ip-adapter-plus_sd15.bin to ip-adapter-plus_sd15.bin
DEBUG:app_logger:Updating pytorch_model.bin to SD1.5\pytorch_model.bin
DEBUG:app_logger:Updating vae-ft-mse-840000-ema-pruned.safetensors to vae-ft-mse-840000-ema-pruned.safetensors
DEBUG:app_logger:Updating epicrealism_pureEvolutionv5.safetensors to epicrealism_pureEvolutionv5.safetensors
DEBUG:app_logger:Updating v3_sd15_sparsectrl_rgb.ckpt to SD1.5\animatediff\v3_sd15_sparsectrl_rgb.ckpt
DEBUG:app_logger:Updating v3_sd15_mm.ckpt to v3_sd15_mm.ckpt
INFO:app_logger:Generating output please wait
got prompt
ERROR:root:Failed to validate prompt for output 281:
ERROR:root:* VHS_SplitImages 354:
ERROR:root:  - Exception when validating inner node: tuple index out of range
ERROR:root:Output will be ignored
model_type EPS
adm 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
clip unexpected: ['clip_l.transformer.text_model.embeddings.position_ids']
left over keys: dict_keys(['model_ema.decay', 'model_ema.num_updates'])
WARNING: Sequential prompt keyframes 2:20 and 3:16 are not monotonously increasing; skipping interpolation.
Requested to load SD1ClipModel
Loading 1 new model
K:\project1\Dough\ComfyUI\comfy\ldm\modules\attention.py:344: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
WARNING: Sequential prompt keyframes 2:20 and 3:16 are not monotonously increasing; skipping interpolation.
WARNING: Sequential prompt keyframes 2:20 and 3:16 are not monotonously increasing; skipping interpolation.
WARNING: Sequential prompt keyframes 2:20 and 3:16 are not monotonously increasing; skipping interpolation.
Requested to load CLIPVisionModelProjection
Loading 1 new model
K:\project1\Dough\ComfyUI\custom_nodes\steerable-motion\SteerableMotion.py:96: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.figure(figsize=(12, 8))
[AnimateDiffEvo] - INFO - Loading motion module v3_sd15_mm.ckpt via Gen2
ValueSchedule:  0     1.25
1     1.25
2     1.25
3     1.25
4     1.25
5     1.25
6     1.25
7     1.25
8     1.25
9     1.25
10    1.25
11    1.25
12    1.25
13    1.25
14    1.25
15    1.25
16    1.25
17    1.25
18    1.25
19    1.25
20    1.25
21    1.25
22    1.25
dtype: float64
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
Leftover VAE keys ['model_ema.decay', 'model_ema.num_updates']
Requested to load AutoencoderKL
Loading 1 new model
[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (23) greater than context_length 16.
[AnimateDiffEvo] - INFO - Using motion module v3_sd15_mm.ckpt:v3.
Requested to load BaseModel
Requested to load SparseControlNet
Requested to load AnimateDiffModel
Loading 3 new models
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [13:03<00:00, 39.18s/it]
Prompt executed in 1097.74 seconds
DEBUG:app_logger:output file list len: 0
DEBUG:app_logger:Process 38476 (Port 4333)
error occured:  list index out of range
Traceback (most recent call last):
  File "K:\project1\Dough\banodoco_runner.py", line 373, in check_and_update_db
    res_output = format_model_output(output, log.model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\project1\Dough\banodoco_runner.py", line 217, in format_model_output
    return [output[-1]]
            ~~~~~~^^^^
IndexError: list index out of range

**Comment by piyushK52** [comment]
hey guys, it's been a couple of months and there have been a lot of fixes/changes pushed to the code. Please check the current code and open a fresh ticket if you encounter any issues. I am closing this one.
